### ISSUE TITLE
LovyanGFX doesn't compile on ESP32-P4 with Arduino 3.3.4 and IDF 5.5.1.251106

### ISSUE THREAD

**Issue by cniedzi** [lovyan03/LovyanGFX#788]
**Carefully written Issues are more likely to be given priority.**
**丁寧に記述された報告は優先して対応される可能性が高くなります。**

## Environment ( 実行環境 )

MCU: ESP32-P4

## Problem Description ( 問題の内容 )

The library doesn't compile with Arduino 3.3.4 and IDF 5.5.1.251106 and throws an error:

```
.pio/libdeps/esp32p4/LovyanGFX/src/lgfx/v1/platforms/esp32p4/Bus_MIPI.cpp: In member function 'virtual bool lgfx::v1::Bus_MIPI::init()':
C:/Users/XXX/.platformio/packages/framework-espidf/components/soc/esp32p4/include/soc/clk_tree_defs.h:469:38: error: cannot convert 'soc_module_clk_t' to 'mipi_dsi_phy_pllref_clock_source_t' {aka 'soc_periph_mipi_dsi_phy_pllref_clk_src_t'} in assignment
  469 | #define MIPI_DSI_PHY_CLK_SRC_DEFAULT SOC_MOD_CLK_PLL_F20M
      |                                      ^~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      soc_module_clk_t
.pio/libdeps/esp32p4/LovyanGFX/src/lgfx/v1/platforms/esp32p4/Bus_MIPI.cpp:49:37: note: in expansion of macro 'MIPI_DSI_PHY_CLK_SRC_DEFAULT'
   49 |     bus_config.phy_clk_src        = MIPI_DSI_PHY_CLK_SRC_DEFAULT;
```
